/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionGrid: typeof import('./src/components/ActionGrid.vue')['default']
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PollGrid: typeof import('./src/components/PollGrid.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
  }
}
